'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Download,Images,Play,RefreshCw,Square,Upload,X,History,Sparkles} from 'lucide-react';
import {toast} from 'sonner';
import ModelSelector,{EMPTY_SELECTION} from '@/components/ModelSelector';
import ImageLightbox from '@/components/ImageLightbox';
import {generateApi,editApi,referencesApi,assetUrl,downloadTaskZip} from '@/lib/api';
import {subscribeTask,type TaskEvent} from '@/lib/task-stream';
import {useAuthStore} from '@/stores/auth';
const DEFAULT={content:'',caption:'',taskType:'diagram',pipelineMode:'demo_full',retrievalSetting:'auto',numCandidates:1,aspectRatio:'16:9',imageSize:'',rounds:3,optimizeInput:false,vectorExport:'none',budget:'',candidateStrategy:'samples',qualityGuard:true,retrieverTopK:10,retrieverPoolSize:'',retrieverContentLimit:'',model:EMPTY_SELECTION};
type Preview={eventId?:string;candidate:number;round:number;url:string;stage:string;description?:string};
const STAGES:Record<string,string>={input_optimizer:'输入整理',retriever:'参考检索',planner:'内容规划',stylist:'视觉设计',visualizer:'图像生成',critic:'图像评审',polish:'精修',queue:'等待供应商',pipeline:'绘图流程',continue:'继续修改',vector_export:'矢量导出',layout_variant:'构图探索'};
const MODES=[['demo_full','完整流程（原版基线）'],['demo_planner_critic','规划 + 评审'],['dev_planner_stylist','规划 + 设计'],['dev_planner','仅规划'],['vanilla','直接生成'],['dev_full','完整流程 + 精修']];
const terminal=(state:string)=>['completed','failed','cancelled'].includes(state);
function nativeRatio(size:string,fallback:string){const parts=/^([1-9][0-9]*)x([1-9][0-9]*)$/.exec(size);if(!parts)return fallback;const w=Number(parts[1]),h=Number(parts[2]);let a=w,b=h;while(b){const c=a%b;a=b;b=c;}return `${w/a}:${h/a}`;}
export default function GeneratePage(){
  const uid=useAuthStore(s=>s.user?.id);const [draft,setDraft]=useState(DEFAULT),[hydrated,setHydrated]=useState(false);
  const [references,setReferences]=useState<{id:number;url:string;file_name:string}[]>([]);
  const [taskId,setTaskId]=useState<string|null>(null),[status,setStatus]=useState('idle'),[submitting,setSubmitting]=useState(false);
  const [extracting,setExtracting]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[connection,setConnection]=useState('');
  const [progress,setProgress]=useState(0),[stage,setStage]=useState(''),[events,setEvents]=useState<TaskEvent[]>([]),[previews,setPreviews]=useState<Preview[]>([]);
  const [results,setResults]=useState<any>(null),[candidate,setCandidate]=useState(0),[version,setVersion]=useState<string|null>(null),[feedback,setFeedback]=useState('');
  const [preserveLayout,setPreserveLayout]=useState(true),[cost,setCost]=useState<any>(null),[advanced,setAdvanced]=useState(false);
  const stream=useRef<(()=>void)|null>(null);const patch=(values:Partial<typeof DEFAULT>)=>setDraft(old=>({...old,...values}));
  const running=status==='pending'||status==='running',draftKey=`paperscholar:draft:${uid||0}`;
  useEffect(()=>{if(!uid)return;try{const cached=localStorage.getItem(draftKey);if(cached)setDraft({...DEFAULT,...JSON.parse(cached)});}catch{/* invalid cached draft */}const id=new URLSearchParams(window.location.search).get('task');if(id){setTaskId(id);setStatus('running');}setHydrated(true);},[uid,draftKey]);
  useEffect(()=>{if(hydrated)try{localStorage.setItem(draftKey,JSON.stringify(draft));}catch{/* storage unavailable */}},[draft,draftKey,hydrated]);
  useEffect(()=>{if(draft.model.imageSizeMode==='fixed'&&draft.model.imageSizeOptions?.length&&!draft.model.imageSizeOptions.includes(draft.imageSize)){const size=draft.model.imageSizeOptions[0];patch({imageSize:size,aspectRatio:nativeRatio(size,draft.aspectRatio)});}},[draft.model.imageSizeMode,draft.model.imageSizeOptions,draft.imageSize]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{
    if(!taskId)return;let live=true,ended=false;
    const refresh=()=>generateApi.getTask(taskId).then(data=>{if(!live)return;setResults(data);if(!ended||terminal(data.status))setStatus(data.status);setProgress(old=>Math.max(old,data.progress||0));if(data.error_message)setError(data.error_message);if(data.cost_details)setCost(data.cost_details);}).catch(e=>{if(live)setError(e.message);});
    void refresh();stream.current=subscribeTask(taskId,event=>{if(!live)return;const data=event.data;
      setEvents(old=>event.id&&old.some(e=>e.id===event.id)?old:[...old,event].slice(-2000));
      if(event.type==='stage'){setStage(data.name||'');if(typeof data.progress==='number')setProgress(old=>Math.max(old,data.progress));}
      if(event.type==='cost')setCost(data);
      if(event.type==='intermediate'&&data.image_url){const preview={eventId:event.id,candidate:Math.max(0,data.candidate_index||0),round:data.round||0,url:assetUrl(data.image_url),stage:data.stage||'visualizer',description:data.description};setPreviews(old=>event.id&&old.some(p=>p.eventId===event.id)?old:[...old,preview]);}
      if(event.type==='done'){ended=true;setStatus(data.status||'completed');setStage('');setConnection('');if(data.message)setError(data.message);void refresh();}
      if(event.type==='error')setError(data.message||'生成过程中发生错误');
    },value=>{if(live)setConnection(value);});
    return()=>{live=false;stream.current?.();stream.current=null;};
  },[taskId]);
  const switchTask=(id:string)=>{stream.current?.();setTaskId(id);setStatus('running');setEvents([]);setPreviews([]);setResults(null);setCandidate(0);setVersion(null);setProgress(0);setCost(null);setError('');window.history.replaceState(null,'',`${window.location.pathname}?task=${encodeURIComponent(id)}`);};
  const size=draft.imageSize||(draft.model.imageSizeMode==='custom'?'auto':undefined);
  const start=async()=>{
    if(draft.content.trim().length<10||draft.caption.trim().length<5){setError('请填写方法/数据（至少 10 字符）与绘图目的（至少 5 字符）');return;}
    setSubmitting(true);setError('');
    try{const data=await generateApi.create({task_type:draft.taskType,content:draft.content,visual_intent:draft.caption,pipeline_mode:draft.pipelineMode,retrieval_setting:references.length?'manual':draft.retrievalSetting,num_candidates:draft.numCandidates,aspect_ratio:nativeRatio(draft.imageSize,draft.aspectRatio),image_size:size,max_critic_rounds:draft.rounds,retriever_top_k:draft.retrieverTopK,retriever_pool_size:draft.retrieverPoolSize===''?null:Number(draft.retrieverPoolSize),retriever_content_limit:draft.retrieverContentLimit===''?null:Number(draft.retrieverContentLimit),optimize_input:draft.optimizeInput,vector_export:draft.vectorExport,budget_usd:draft.budget?Number(draft.budget):undefined,candidate_strategy:draft.candidateStrategy,quality_guard:draft.qualityGuard,reference_image_ids:references.map(r=>r.id),chat_model_name:draft.model.chatModelName||undefined,chat_key_id:draft.model.chatKeyId||undefined,image_model_name:draft.model.imageModelName||undefined,image_key_id:draft.model.imageKeyId||undefined});switchTask(data.task_id);}catch(e:any){setError(e.message||'无法创建任务');}finally{setSubmitting(false);}
  };
  const cancel=async()=>{if(!taskId)return;try{const data=await generateApi.cancel(taskId);setStatus('cancelled');toast.info(data.message);}catch(e:any){setError(e.message);}};
  const candidates=useMemo(()=>{const map=new Map<number,{index:number;url?:string;result?:any}>();previews.forEach(p=>map.set(p.candidate,{index:p.candidate,url:p.url}));(results?.results||[]).forEach((r:any)=>map.set(r.candidate_index,{index:r.candidate_index,url:r.image_url?assetUrl(r.image_url):undefined,result:r}));return [...map.values()].sort((a,b)=>a.index-b.index);},[previews,results]);
  const active=candidates.find(c=>c.index===candidate)||candidates[0],versions=previews.filter(p=>p.candidate===(active?.index??candidate));
  const chosen=version?versions.find(p=>p.eventId===version):undefined,activeUrl=chosen?.url||active?.url;
  const continueTask=async()=>{if(!taskId||!active?.result||feedback.trim().length<3)return;setSubmitting(true);setError('');try{const next=await generateApi.continueTask(taskId,{result_id:active.result.id,feedback,source_event_id:chosen?.eventId?Number(chosen.eventId):undefined,preserve_layout:preserveLayout,quality_guard:draft.qualityGuard,additional_critic_rounds:Math.max(1,draft.rounds),image_size:size,vector_export:draft.vectorExport,budget_usd:draft.budget?Number(draft.budget):undefined});setFeedback('');switchTask(next.task_id);}catch(e:any){setError(e.message||'无法继续修改；原有结果已保留');}finally{setSubmitting(false);}};
  const retryTask=async()=>{if(!taskId)return;setSubmitting(true);setError('');try{const next=await generateApi.retryTask(taskId);switchTask(next.task_id);}catch(e:any){setError(e.message||'无法重试任务');}finally{setSubmitting(false);}};
  const extract=async(file:File)=>{setExtracting(true);try{const body=new FormData();body.append('file',file);if(draft.model.chatModelName)body.append('chat_model_name',draft.model.chatModelName);if(draft.model.chatKeyId)body.append('chat_key_id',String(draft.model.chatKeyId));patch({content:(await editApi.extractMethodology(body)).methodology});}catch(e:any){setError(e.message);}finally{setExtracting(false);}};
  const upload=async(file:File)=>{if(references.length>=10){toast.error('最多上传 10 张参考图');return;}setUploading(true);try{const data=await referencesApi.upload(file);setReferences(old=>[...old,data]);}catch(e:any){setError(e.message);}finally{setUploading(false);}};
  const description=chosen?.description||[...events].reverse().find(e=>e.type==='intermediate'&&['stylist','planner','layout_variant'].includes(e.data.stage)&&[active?.index,-1,undefined].includes(e.data.candidate_index))?.data.content;
  return <div className="max-w-[1700px] mx-auto space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold tracking-widest text-primary-600 mb-1">RESEARCH ILLUSTRATION STUDIO</p><h1 className="text-2xl font-semibold">学术参考图工作台</h1><p className="text-sm text-[var(--text-muted)] mt-1">先探索构图，再比较与精修。原始图片和每轮版本都会保留。</p></div><div className="flex gap-2">{running&&<button className="btn-ghost flex items-center gap-2" onClick={cancel}><Square size={14}/>停止</button>}<button disabled={running||submitting||extracting} className="btn-primary flex items-center gap-2" onClick={start}>{submitting?<RefreshCw size={16} className="animate-spin"/>:<Play size={16}/>} {running?'正在生成':'生成参考图'}</button></div></header>
    {error&&<div role="alert" className="error-box flex justify-between gap-3"><p className="whitespace-pre-wrap">{error}</p><button aria-label="关闭错误提示" onClick={()=>setError('')}><X size={16}/></button></div>}
    <div className="grid xl:grid-cols-[285px_minmax(0,1fr)_270px] gap-4 items-start">
      <aside className="workspace-panel"><div className="flex rounded-lg bg-[var(--bg-main)] p-1 gap-1">{[['diagram','方法示意图'],['plot','数据统计图']].map(([id,label])=><button disabled={running} key={id} onClick={()=>patch({taskType:id,pipelineMode:'demo_full'})} className={`flex-1 py-2 text-sm rounded-md ${draft.taskType===id?'bg-[var(--bg-panel)] shadow-sm font-medium':'text-[var(--text-muted)]'}`}>{label}</button>)}</div>
        <div><div className="flex justify-between items-center mb-2"><label className="field-label mb-0" htmlFor="source-content">{draft.taskType==='diagram'?'研究方法':'原始数据'}</label>{draft.taskType==='diagram'&&<label className="text-xs text-primary-600 cursor-pointer">{extracting?'提取中…':'从论文提取'}<input className="sr-only" type="file" accept=".pdf,.md,.txt,.tex" disabled={extracting||running} onChange={e=>{const f=e.target.files?.[0];if(f)void extract(f);e.target.value='';}}/></label>}</div><textarea id="source-content" className="input-tech w-full min-h-[180px] resize-y" value={draft.content} onChange={e=>patch({content:e.target.value})} placeholder={draft.taskType==='diagram'?'粘贴方法内容、模块关系和关键机制…':'粘贴 CSV、JSON 或数据表…'}/></div>
        <label className="block"><span className="field-label">这张图要表达什么？</span><textarea className="input-tech w-full" rows={3} value={draft.caption} onChange={e=>patch({caption:e.target.value})} placeholder="要突出什么？哪些内容不必放进图中？"/></label>
        {draft.taskType==='diagram'&&<section><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">视觉参考</h3><span className="text-xs text-[var(--text-muted)]">{references.length}/10</span></div><p className="text-xs text-[var(--text-muted)] mt-1 mb-3">借鉴布局与风格，不复制科学结论。</p><div className="flex flex-wrap gap-2">{references.map(r=><div key={r.id} className="relative"><img src={assetUrl(r.url)} alt={r.file_name} className="w-16 h-16 object-contain bg-white border rounded-lg"/><button aria-label={`移除参考图 ${r.file_name}`} className="absolute -top-1 -right-1 p-0.5 rounded-full border bg-[var(--bg-panel)]" onClick={()=>setReferences(old=>old.filter(x=>x.id!==r.id))}><X size={12}/></button></div>)}</div><label className="mt-3 flex items-center justify-center gap-2 border border-dashed border-[var(--border-main)] p-3 rounded-lg cursor-pointer text-sm hover:bg-[var(--bg-hover)]"><Upload size={15}/>{uploading?'上传中…':'上传参考图'}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading||running} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></label></section>}
        <div className="border-t border-[var(--border-subtle)] pt-4"><ModelSelector value={draft.model} showImage={draft.taskType==='diagram'} disabled={running} onChange={model=>patch({model})}/></div>
        <button className="flex justify-between w-full text-sm text-[var(--text-muted)]" onClick={()=>setAdvanced(x=>!x)}>生成参数与高级设置<span>{advanced?'−':'+'}</span></button>
        {advanced&&<div className="space-y-4 pt-4 border-t border-[var(--border-subtle)]">
          <label className="block"><span className="field-label">流程</span><select className="input-tech w-full" value={draft.pipelineMode} onChange={e=>patch({pipelineMode:e.target.value})}>{MODES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
          <div className="grid grid-cols-2 gap-3"><label><span className="field-label">候选数量</span><input aria-label="候选数量" className="input-tech w-full" type="number" min={1} max={20} value={draft.numCandidates} onChange={e=>patch({numCandidates:Number(e.target.value)})}/></label><label><span className="field-label">评审轮数</span><input aria-label="评审轮数" className="input-tech w-full" type="number" min={0} max={5} value={draft.rounds} onChange={e=>patch({rounds:Number(e.target.value)})}/></label></div>
          <label className="block"><span className="field-label">候选策略</span><select className="input-tech w-full" value={draft.candidateStrategy} onChange={e=>patch({candidateStrategy:e.target.value})}><option value="samples">同方案多次生成（原版）</option><option value="layouts">探索构图（保留候选 1 基线）</option></select></label>
          {draft.taskType==='diagram'&&(draft.model.imageSizeMode==='fixed'?<label className="block"><span className="field-label">实际输出尺寸</span><select className="input-tech w-full" value={draft.imageSize} onChange={e=>patch({imageSize:e.target.value,aspectRatio:nativeRatio(e.target.value,draft.aspectRatio)})}>{draft.model.imageSizeOptions?.map(x=><option key={x}>{x}</option>)}</select></label>:draft.model.imageSizeMode==='custom'?<label className="block"><span className="field-label">原生图片尺寸</span><input list="native-sizes" className="input-tech w-full" value={draft.imageSize} placeholder="auto 或 1536x864" onChange={e=>patch({imageSize:e.target.value})}/><datalist id="native-sizes">{['auto','1024x1024','1536x1024','1536x864','2048x1152'].map(x=><option key={x}>{x}</option>)}</datalist><p className="text-xs text-[var(--text-muted)] mt-1">按供应商规格填写；不会把新模型限制在旧尺寸菜单中。</p></label>:<div className="grid grid-cols-2 gap-3"><label><span className="field-label">画面比例</span><select className="input-tech w-full" value={draft.aspectRatio} onChange={e=>patch({aspectRatio:e.target.value})}>{['1:1','16:9','4:3','3:2','21:9','2:3','9:16'].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="field-label">分辨率</span><select className="input-tech w-full" value={draft.imageSize} onChange={e=>patch({imageSize:e.target.value})}><option value="">服务默认</option>{['1K','2K','4K'].map(x=><option key={x}>{x}</option>)}</select></label></div>)}
          <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={draft.qualityGuard} onChange={e=>patch({qualityGuard:e.target.checked})}/>比较新旧版本后再采纳修改</label><p className="text-xs text-[var(--text-muted)]">会增加评审调用。比较失败时保留旧版；模型评价不能替代人工核验。</p>
          <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={draft.optimizeInput} onChange={e=>patch({optimizeInput:e.target.checked})}/>整理输入后再规划</label>
          <label className="block"><span className="field-label">估算预算上限（美元）</span><input className="input-tech w-full" type="number" min="0.01" step="0.01" value={draft.budget} onChange={e=>patch({budget:e.target.value})} placeholder="不设置"/><span className="text-xs text-[var(--text-muted)]">这是估算停止阈值，不是实际账单硬限额。</span></label>
          <label className="block"><span className="field-label">矢量导出</span><select className="input-tech w-full" value={draft.vectorExport} onChange={e=>patch({vectorExport:e.target.value})}>{[['none','不导出'],['svg','SVG'],['pdf','PDF'],['both','SVG + PDF']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><span className="text-xs text-[var(--text-muted)]">示意图矢量导出是独立重建，可能与原图不一致。</span></label>
          <details className="text-sm"><summary className="cursor-pointer text-[var(--text-muted)]">参考检索参数</summary><div className="space-y-3 mt-3"><select aria-label="参考检索模式" className="input-tech w-full" value={draft.retrievalSetting} onChange={e=>patch({retrievalSetting:e.target.value})}>{[['auto','自动检索'],['none','不检索'],['random','随机参考']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><label className="block">参考数量<input className="input-tech w-full" type="number" min={1} max={20} value={draft.retrieverTopK} onChange={e=>patch({retrieverTopK:Number(e.target.value)})}/></label><label className="block">候选池（空为默认，0 为全部）<input className="input-tech w-full" type="number" min={0} value={draft.retrieverPoolSize} onChange={e=>patch({retrieverPoolSize:e.target.value})}/></label><label className="block">每条参考截断字符数（空为不截断）<input className="input-tech w-full" type="number" min={1} value={draft.retrieverContentLimit} onChange={e=>patch({retrieverContentLimit:e.target.value})}/></label></div></details>
        </div>}
      </aside>
      <main className="min-w-0 space-y-4">
        {(running||terminal(status))&&<div className="surface p-4"><div className="flex items-center justify-between text-sm"><span className="font-medium">{running?(STAGES[stage]||stage||'准备任务'):status==='completed'?'生成完成':status==='cancelled'?'已停止后续执行':'本次运行未完成'}</span><span className="text-[var(--text-muted)]">{Math.round(progress*100)}%</span></div><div className="mt-3 h-1.5 rounded-full bg-[var(--bg-inset)] overflow-hidden"><div className="h-full bg-primary-500 transition-all" style={{width:`${Math.min(100,progress*100)}%`}}/></div>{running&&<p className="text-xs text-[var(--text-muted)] mt-2">{connection} · 已完成的图片会陆续出现，刷新可恢复任务。</p>}{(status==='failed'||status==='cancelled')&&<button className="btn-primary mt-3" disabled={submitting} onClick={retryTask}>{submitting?'正在重新提交…':'继续重试本次任务'}</button>}</div>}
        {!candidates.length?<div className="surface min-h-[450px] flex flex-col items-center justify-center text-center p-8"><div className="p-4 rounded-2xl bg-primary-50 dark:bg-primary-500/10 mb-5"><Images size={32} className="text-primary-600"/></div><h2 className="text-lg font-semibold">{running?'正在准备第一张参考图':'从方法到有表达力的构图'}</h2><p className="text-sm text-[var(--text-muted)] max-w-sm mt-3 leading-relaxed">{running?'规划、参考检索与生成进度会显示在这里。':'填写左侧内容，先生成原版基线，或探索几种不同构图。'}</p>{!running&&<button className="btn-ghost mt-6 flex items-center gap-2" onClick={()=>{patch({numCandidates:4,candidateStrategy:'layouts'});setAdvanced(true);toast.info('已设置 4 张候选，第一张保留原版规划');}}><Sparkles size={15}/>设置 4 种构图候选</button>}</div>:<>
          <div className="flex justify-between items-center gap-3"><h2 className="text-sm font-semibold">候选参考图 · {candidates.length}</h2>{results?.results?.length>0&&<button className="text-sm text-primary-600 flex items-center gap-1" onClick={()=>taskId&&downloadTaskZip(taskId).catch(e=>toast.error(e.message))}><Download size={14}/>全部下载</button>}</div>
          <div className="grid grid-cols-2 2xl:grid-cols-3 gap-3">{candidates.map(c=><button className={`surface overflow-hidden text-left hover:shadow-md transition-shadow ${active?.index===c.index?'ring-2 ring-primary-500 ring-offset-2 ring-offset-[var(--bg-main)]':''}`} key={c.index} onClick={()=>{setCandidate(c.index);setVersion(null);}}>{c.url?<img src={c.url} alt={`候选 ${c.index+1}`} className="w-full aspect-[3/2] object-contain bg-white p-2"/>:<div className="aspect-[3/2] flex items-center justify-center">暂无图片</div>}<div className="p-3"><span className="text-sm font-medium">候选 {c.index+1}</span><p className="text-xs text-[var(--text-muted)] mt-1">{c.index===0?'原版规划基线':(results?.request_params?.candidate_strategy||draft.candidateStrategy)==='layouts'?'构图探索':'独立采样'} · {c.result?'已保存':'中间版本'}</p></div></button>)}</div>
          {activeUrl&&<div className="surface p-3"><div className="flex justify-between items-center px-1 pb-3 gap-2"><span className="text-sm font-medium">候选 {(active?.index||0)+1} · {chosen?`历史版本 ${chosen.round}`:'当前结果'}</span><a className="text-sm text-primary-600" href={activeUrl} target="_blank" rel="noreferrer" download>查看原图</a></div><ImageLightbox src={activeUrl} alt="当前学术参考图"><img src={activeUrl} alt="当前学术参考图" className="w-full bg-white rounded-lg object-contain max-h-[650px] cursor-zoom-in"/></ImageLightbox></div>}
        </>}
        {!!events.length&&<details className="surface p-4 text-sm"><summary className="cursor-pointer text-[var(--text-muted)]">运行日志与诊断 · {events.length}</summary><div className="max-h-72 overflow-auto mt-3 space-y-2">{events.map((e,i)=><div key={e.id||`local-${i}`} className="border-b border-[var(--border-subtle)] pb-2 text-xs"><span className="font-medium">{e.data.candidate_index>=0?`候选 ${e.data.candidate_index+1} · `:''}{STAGES[e.data.name||e.data.stage]||e.type}</span><p className="text-[var(--text-muted)] whitespace-pre-wrap break-words mt-1">{e.data.content||e.data.reason||e.data.message||e.data.status||''}</p></div>)}</div></details>}
      </main>
      <aside className="workspace-panel"><div><h2 className="text-sm font-semibold">选中方案</h2><p className="text-sm text-[var(--text-muted)] mt-1">{active?`候选 ${active.index+1}`:'生成后选择一张参考图'}</p></div>
        {cost&&<div className="p-3 rounded-lg bg-[var(--bg-main)]"><span className="text-xs text-[var(--text-muted)]">本次估算费用</span><p className="text-lg font-semibold mt-1">${Number(cost.total_usd||0).toFixed(4)}</p><p className="text-xs text-[var(--text-muted)]">{cost.num_calls||0} 次调用 · 以供应商账单为准</p></div>}
        <section className="space-y-3"><h3 className="text-sm font-semibold">基于此图修改</h3><textarea aria-label="修改要求" className="input-tech w-full" rows={4} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="例如：保留布局，突出核心模块，让信息流更清楚"/><select aria-label="修改方式" className="input-tech w-full" value={preserveLayout?'preserve':'redesign'} onChange={e=>setPreserveLayout(e.target.value==='preserve')}><option value="preserve">保留布局，带原图修改</option><option value="redesign">允许重新构图</option></select><p className="text-xs text-[var(--text-muted)]">保留布局需要图片编辑能力；失败时不会丢掉原图重画。</p><button className="btn-primary w-full flex justify-center items-center gap-2" disabled={running||submitting||!active?.result||feedback.trim().length<3} onClick={continueTask}>生成修改版本<ArrowRight size={15}/></button></section>
        <section className="border-t border-[var(--border-subtle)] pt-4"><h3 className="text-sm font-semibold flex items-center gap-2 mb-3"><History size={14}/>版本历史</h3>{versions.length?<div className="space-y-2"><button className={`w-full text-left text-sm rounded-lg p-2 ${!version?'bg-primary-50 dark:bg-primary-500/10':''}`} onClick={()=>setVersion(null)}>当前结果</button>{versions.map((v,i)=><button key={v.eventId||v.url} className={`w-full flex items-center gap-3 text-left p-2 rounded-lg ${version===v.eventId?'bg-primary-50 dark:bg-primary-500/10':'hover:bg-[var(--bg-hover)]'}`} onClick={()=>setVersion(v.eventId||null)}><img src={v.url} alt={`第 ${i+1} 个版本`} className="w-14 h-10 object-contain bg-white rounded border"/><span className="text-xs">{STAGES[v.stage]||v.stage} · 第 {v.round} 轮</span></button>)}</div>:<p className="text-xs text-[var(--text-muted)]">每轮图片会保留在这里。</p>}</section>
        {description&&<details className="border-t border-[var(--border-subtle)] pt-4"><summary className="text-sm cursor-pointer">查看设计说明</summary><p className="whitespace-pre-wrap text-xs text-[var(--text-secondary)] mt-3 max-h-80 overflow-auto">{description}</p></details>}
        {active?.result?.svg_url&&<a className="text-sm text-primary-600 block" href={assetUrl(active.result.svg_url)} download>下载 SVG（独立重建）</a>}{active?.result?.pdf_url&&<a className="text-sm text-primary-600 block" href={assetUrl(active.result.pdf_url)} download>下载 PDF</a>}
      </aside>
    </div>
  </div>;
}
